### ISSUE TITLE
module 'pysynth' has no attribute 'make_wav'?

### ISSUE THREAD

**Issue by bright135** [mdoege/PySynth#1]
1 have installed pysynth

$ pip3 search PySynth
pysynth (0.0.4) - Dataset synthesis for Python
INSTALLED: 0.0.4 (latest)
\033[012;32m][\u@\t]\033[012;33m]\w[\033[012;36m]$[\033[00m]  
$ pip3 install PySynth
Requirement already satisfied: PySynth in /usr/local/lib/python3.7/site-packages (0.0.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/site-packages (from PySynth) (1.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from PySynth) (1.18.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/site-packages (from PySynth) (1.4.1)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.7/site-packages (from PySynth) (0.22.2.post1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/site-packages (from pandas->PySynth) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/site-packages (from pandas->PySynth) (2.8.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/site-packages (from scikit-learn>=0.22->PySynth) (0.14.1)
Requirement already satisfied: six>=1.5 in ./Library/Python/3.7/lib/python/site-packages (from python-dateutil>=2.6.1->pandas->PySynth) (1.14.0)

**Comment by CiChenEe** [comment]
1 have installed pysynth

pip3 search PySynth
pysynth (0.0.4)  - Dataset synthesis for Python
  INSTALLED: 0.0.4 (latest)
\033[012;32m\][\u@\t]\033[012;33m\]\w\[\033[012;36m\]$\[\033[00m\] pip3 install PySynth
Requirement already satisfied: PySynth in /usr/local/lib/python3.7/site-packages (0.0.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/site-packages (from PySynth) (1.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from PySynth) (1.18.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/site-packages (from PySynth) (1.4.1)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.7/site-packages (from PySynth) (0.22.2.post1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/site-packages (from pandas->PySynth) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/site-packages (from pandas->PySynth) (2.8.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/site-packages (from scikit-learn>=0.22->PySynth) (0.14.1)
Requirement already satisfied: six>=1.5 in ./Library/Python/3.7/lib/python/site-packages (from python-dateutil>=2.6.1->pandas->PySynth) (1.14.0)

**Comment by mdoege** [comment]
I have removed PySynth from PyPy, so don't use pip. I think you need to install it with "python setup.py install" now...
