### ISSUE TITLE
add upload package to pypi

### ISSUE THREAD

**Issue by vdwees** [mdoege/PySynth#16]
I would like to install PySynth via pypi. It seems like pypi has this package registered, but attempting to install via pip fails: 

```
> pip search "pysynth"
PySynth (2.3)  - A simple music synthesizer for Python 3
> pip install pysynth
Collecting pysynth
  Could not find a version that satisfies the requirement pysynth (from versions: )
No matching distribution found for pysynth
```
According to StackOverflow, this needs to happen: 
```
> python3 setup.py register sdist upload
```
See: https://stackoverflow.com/questions/45105264/published-pypi-package-shows-up-on-search-but-wont-pip-install

**Comment by mdoege** [comment]
OK, thanks for reporting. I've run the command. Does it work now?

**Comment by vdwees** [comment]
Indeed it does! Thanks!
