### ISSUE TITLE
support python3

### ISSUE THREAD

**Issue by nateGeorge** [mdoege/PySynth#5]
I'd like to use this in python 3, so far it looks like the print functions need to be changed.

**Comment by mdoege** [comment]
Just run "2to3 -n -w  ." in the PySynth directory, that should convert it to a working Python 3 version.

Maybe I will modify my code to run on both Python 2 and 3, but I have to test that first. 2to3 makes some changes besides the print function.

**Comment by ginoskotheon** [comment]
I keep getting the following error:


  File "C:/IPythonCode/pysynth.py", line 186, in render2
    .5*harm*asin(float(x)/(l[0]/4.)))/4.*fac*vol*dfac*volfac)

TypeError: Can't convert 'bytes' object to str implicitly

I'm using Python 3.5. Could you help?

**Comment by nateGeorge** [comment]
I actually started writing my own python3 converter (just for the print functions) and discovered that I had to use a weird encoding I'd never encountered.  This worked to open the file in python3:

`with open(file, 'r', encoding = 'ISO-8859-1') as rFile:`

https://github.com/nateGeorge/python2-python3-syntax-updator

**Comment by mdoege** [comment]
Writing your own converter is pointless because 2to3 comes with every Python 3 installation and fixes everything, not just print statements. But even with 2to3, it is not guaranteed that the converted code with actually work (although I'm pretty sure in the case of PySynth it does)…

**Comment by mdoege** [comment]
@ginoskotheon Did you convert the code with 2to3 or what are you using? That line of code only uses numbers, not strings, so the error message is a bit strange.

**Comment by mdoege** [comment]
@nateGeorge @ginoskotheon OK, the latest git version of PySynth is now compatible with Python 3. Please report any problems.

**Comment by ginoskotheon** [comment]
@mdoege Yes. I used the 2to3. I'll try the new git version. Thanks.

**Comment by nateGeorge** [comment]
@mdoege , thanks, it's working.
