### ISSUE TITLE
setup not working correctly

### ISSUE THREAD

**Issue by jcollins1007** [mdoege/PySynth#9]
I downloaded the tar file and extracted to my /home/<user> folder, then ran "python3 setup.py install". I ran the python3 shell, and tried "import pysynth_b" and it said that there was no module named "mixfiles." I corrected this by editing the setup.py file and adding "mixfiles" to the module list. I reran the setup.py and it worked. I'm not sure how many others there are that need to be added for basic functionality. My setup file is attached.
[setup.py.zip](https://github.com/mdoege/PySynth/files/403146/setup.py.zip)

**Comment by mdoege** [comment]
https://github.com/mdoege/PySynth/commit/7c3aa27619cffece12b8bae44095876fd9a6b118 should have fixed this now. Thanks for reporting!
